package org.br.agro.infra.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.UUID;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@DynamoDBTable(tableName="quotationdb")
public class QuotationEntity implements Serializable {
    private static final long serialVersionUID = 1L;

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    private UUID id;

    @DynamoDBAttribute(attributeName="Date")
    private Date date;

    @DynamoDBAttribute(attributeName="CurrencyPrice")
    private BigDecimal currencyPrice;

    @DynamoDBAttribute(attributeName="pctChange")
    private String pctChange;

    @DynamoDBAttribute(attributeName="pair")
    private String pair;

}
