package org.br.agro.infra.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.br.agro.infra.entity.converter.LocalDateTimeConverter;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@DynamoDBTable(tableName="Quotation")
public class QuotationEntity implements Serializable {
    private static final long serialVersionUID = 1L;

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    private UUID id;

    @DynamoDBAttribute(attributeName="Date")
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime date;

    @DynamoDBAttribute(attributeName="CurrencyPrice")
    private BigDecimal currencyPrice;

    @DynamoDBAttribute(attributeName="pctChange")
    private String pctChange;

    @DynamoDBAttribute(attributeName="pair")
    private String pair;

}
